name: Build & Push Frontend Image

on:
  pull_request:
    types: [closed]
    branches: [main]

env:
  IMAGE_NAME: osmity/osmity-web-frontend

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags

      - name: Determine next frontend version
        shell: bash
        run: |
          LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)
          if [ -z "$LATEST_TAG" ]; then
            MAJOR=0
            MINOR=0
            PATCH=0
          else
            VERSION=${LATEST_TAG#v}
            IFS='.' read MAJOR MINOR PATCH <<< "$VERSION"
          fi

          LABELS="${{ join(github.event.pull_request.labels.*.name, ' ') }}"

          if [[ "$LABELS" == *"release:major"* ]]; then
            MAJOR=$((MAJOR+1))
            MINOR=0
            PATCH=0
          elif [[ "$LABELS" == *"release:minor"* ]]; then
            MINOR=$((MINOR+1))
            PATCH=0
          else
            PATCH=$((PATCH+1))
          fi

          echo "FRONT_VERSION=v$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV

      - name: Set frontend build metadata
        run: |
          echo "FRONT_BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "FRONT_COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push frontend image
        run: |
          docker build \
            --no-cache \
            --build-arg APP_ENV=prod \
            --build-arg FRONT_VERSION=${FRONT_VERSION} \
            --build-arg FRONT_BUILD_TIME=${FRONT_BUILD_TIME} \
            --build-arg FRONT_COMMIT_SHA=${FRONT_COMMIT_SHA} \
            -t $IMAGE_NAME:${FRONT_VERSION} .

          docker push $IMAGE_NAME:${FRONT_VERSION}
