name: Deploy Frontend (dev/prod)

on:
  push:
    branches: ["main", "prod"]

env:
  IMAGE_NAME: osmity/osmity-web-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set variables
        run: |
          if [ "${GITHUB_REF##*/}" = "prod" ]; then
            echo "TAG=prod" >> $GITHUB_ENV
            echo "DEPLOY_DIR=prod" >> $GITHUB_ENV
          else
            echo "TAG=dev" >> $GITHUB_ENV
            echo "DEPLOY_DIR=dev" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build --no-cache -t $IMAGE_NAME:${TAG} .

      - name: Push image
        run: |
          docker push $IMAGE_NAME:${TAG}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/Osmity/${DEPLOY_DIR}
            docker compose pull
            docker compose up -d
            docker system prune -f
