name: Deploy Frontend (prod)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy tagged frontend
        uses: appleboy/ssh-action@v1.0.3
        env:
          FRONT_VERSION: ${{ github.ref_name }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: FRONT_VERSION
          script: |
            cd ~/Osmity/prod
            echo "FRONT_VERSION=${FRONT_VERSION}" > .env
            echo "Deploying frontend version: ${FRONT_VERSION}"
            docker compose pull frontend
            docker compose up -d frontend
            docker system prune -f
